# Generated by Django 6.1 on 2026-09-24 07:44

import django.utils.timezone
from django.db import migrations, models


def backfill_sent_at(apps, schema_editor):
    """Existing invitations were sent when they were created - without this
    they'd get the migration's run time and silently outlive their expiry."""
    Invitation = apps.get_model("users", "Invitation")
    Invitation.objects.update(sent_at=models.F("created"))


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_invitation_email_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="sent_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(backfill_sent_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("EXPIRED", "Expired"),
                    ("REVOKED", "Revoked"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
