# Generated by Django 6.1.2 on 2026-10-08 18:28

from django.db import migrations, models


def verify_existing_accounts(apps, schema_editor):
    """Accounts from before verification existed keep working: they count as
    verified since they were created."""
    User = apps.get_model("users", "User")
    User.objects.update(email_verified_at=models.F("created"))


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(verify_existing_accounts, migrations.RunPython.noop),
    ]
