# Generated by Django 6.1 on 2026-08-17 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documentpermission",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="projectpermission",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="documentpermission",
            constraint=models.UniqueConstraint(
                fields=("document", "user"),
                name="unique_document_user_permission",
                violation_error_message="This user already has a permission assigned for this document.",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"),
                name="unique_organization_project_name",
                violation_error_message="A project with this name already exists in your organization.",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectpermission",
            constraint=models.UniqueConstraint(
                fields=("project", "user"),
                name="unique_project_user_permission",
                violation_error_message="This user already has a permission assigned for this project.",
            ),
        ),
    ]
