# Generated by Django 6.1 on 2026-10-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_visibility_personal_documents_access_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="revision",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
