# Generated by Django 6.1.2 on 2026-10-09 04:01

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


def record_current_versions(apps, schema_editor):
    """Starts each existing document's history with its text as it is now.
    Who saved the latest edit was never recorded, so it's credited to the
    document's creator."""
    Document = apps.get_model("projects", "Document")
    DocumentVersion = apps.get_model("projects", "DocumentVersion")
    DocumentVersion.objects.bulk_create(
        DocumentVersion(
            document_id=document.pk,
            revision=document.revision,
            title=document.title,
            content=document.content,
            created_by_id=document.created_by_id,
        )
        for document in Document.objects.iterator()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_document_revision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("revision", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="projects.document",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "revision"),
                        name="unique_document_revision_version",
                    )
                ],
            },
        ),
        migrations.RunPython(record_current_versions, migrations.RunPython.noop),
    ]
