# Generated by Django 6.1 on 2026-09-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="last_expiry_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
