# Generated by Django 6.1.2 on 2026-10-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_last_expiry_reminder_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="deletion_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
