# Generated by Django 6.1.2 on 2026-10-09 14:48

from django.db import migrations, models


def mark_built_exports_ready(apps, schema_editor):
    """Exports from before the status existed are ready once their file is."""
    OrganizationExport = apps.get_model("organizations", "OrganizationExport")
    OrganizationExport.objects.exclude(file="").update(status="READY")


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_organization_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationexport",
            name="status",
            field=models.CharField(
                choices=[
                    ("BUILDING", "Building"),
                    ("READY", "Ready"),
                    ("FAILED", "Failed"),
                ],
                default="BUILDING",
                max_length=10,
            ),
        ),
        migrations.RunPython(mark_built_exports_ready, migrations.RunPython.noop),
    ]
