# Generated by Django 6.1.2 on 2026-10-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_organizationexport_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="require_two_factor",
            field=models.BooleanField(default=False),
        ),
    ]
