/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Lists the org's documents (``?search=`` matches title, ``?project=``
         *     narrows to one project); creates one either under a project the caller has
         *     at least Editor access to, or - with no ``project`` given - as a personal
         *     document any org member may create. The creator always becomes Owner.
         */
        get: operations["api_v1_documents_list"];
        put?: never;
        /**
         * @description Lists the org's documents (``?search=`` matches title, ``?project=``
         *     narrows to one project); creates one either under a project the caller has
         *     at least Editor access to, or - with no ``project`` given - as a personal
         *     document any org member may create. The creator always becomes Owner.
         */
        post: operations["api_v1_documents_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Retrieve/update/soft-delete a document. Access resolves via
         *     ``DocumentPermission`` alone - explicit grant, else implicit Viewer if the
         *     document is public, else nothing: read needs Viewer, write Editor, delete
         *     Owner. A document outside the requester's organization, or a private one
         *     they have no resolvable access to, is a 404 either way; one they can see
         *     but can't act on at the requested level is a 403.
         */
        get: operations["api_v1_documents_retrieve"];
        /**
         * @description Retrieve/update/soft-delete a document. Access resolves via
         *     ``DocumentPermission`` alone - explicit grant, else implicit Viewer if the
         *     document is public, else nothing: read needs Viewer, write Editor, delete
         *     Owner. A document outside the requester's organization, or a private one
         *     they have no resolvable access to, is a 404 either way; one they can see
         *     but can't act on at the requested level is a 403.
         */
        put: operations["api_v1_documents_update"];
        post?: never;
        /**
         * @description Retrieve/update/soft-delete a document. Access resolves via
         *     ``DocumentPermission`` alone - explicit grant, else implicit Viewer if the
         *     document is public, else nothing: read needs Viewer, write Editor, delete
         *     Owner. A document outside the requester's organization, or a private one
         *     they have no resolvable access to, is a 404 either way; one they can see
         *     but can't act on at the requested level is a 403.
         */
        delete: operations["api_v1_documents_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Retrieve/update/soft-delete a document. Access resolves via
         *     ``DocumentPermission`` alone - explicit grant, else implicit Viewer if the
         *     document is public, else nothing: read needs Viewer, write Editor, delete
         *     Owner. A document outside the requester's organization, or a private one
         *     they have no resolvable access to, is a 404 either way; one they can see
         *     but can't act on at the requested level is a 403.
         */
        patch: operations["api_v1_documents_partial_update"];
        trace?: never;
    };
    "/api/v1/documents/{id}/access-requests/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Lists a document's pending access requests (Owner-only), or files a new
         *     one. A Viewer who can see the document - typically because it's public -
         *     may request Editor access; a document the caller can't resolve any access
         *     to is a 404, same as everywhere else private resources are hidden.
         */
        get: operations["api_v1_documents_access_requests_list"];
        put?: never;
        /**
         * @description Lists a document's pending access requests (Owner-only), or files a new
         *     one. A Viewer who can see the document - typically because it's public -
         *     may request Editor access; a document the caller can't resolve any access
         *     to is a 404, same as everywhere else private resources are hidden.
         */
        post: operations["api_v1_documents_access_requests_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}/access-requests/{request_id}/approve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Owner-only. Upgrades the requester to Editor and marks the request
         *     approved, inside one transaction. Approval only ever raises access: a
         *     requester who has been given Editor or Owner since asking keeps it.
         */
        post: operations["api_v1_documents_access_requests_approve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}/access-requests/{request_id}/deny/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Owner-only. Marks the request denied without touching permissions. */
        post: operations["api_v1_documents_access_requests_deny_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}/restore/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Reverses a soft-delete. Unlike ``ProjectRestoreAPIView`` (admin-only),
         *     document creation isn't admin-gated, so restoring requires the same
         *     Owner-level access that deleting it did. A document whose project is in
         *     the trash can't be restored on its own - it would stay hidden.
         */
        post: operations["api_v1_documents_restore_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}/share/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Lists a document's ``DocumentPermission`` grants, or grants/updates
         *     one for a target user - same convention as ``ProjectShareAPIView``.
         *     Owner-level access is resolved via ``resolve_access`` (explicit grant, or
         *     implicit Viewer on a public document - never enough to share, since
         *     sharing needs ``Action.RESHARE``).
         */
        get: operations["api_v1_documents_share_list"];
        put?: never;
        /**
         * @description Lists a document's ``DocumentPermission`` grants, or grants/updates
         *     one for a target user - same convention as ``ProjectShareAPIView``.
         *     Owner-level access is resolved via ``resolve_access`` (explicit grant, or
         *     implicit Viewer on a public document - never enough to share, since
         *     sharing needs ``Action.RESHARE``).
         */
        post: operations["api_v1_documents_share_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}/share/{user_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Revokes a ``DocumentPermission`` outright (row deletion, not a
         *     soft-delete); access then falls back to implicit Viewer if the document is
         *     public, or to nothing. Owner-level access required; refuses to remove the
         *     document's last Owner.
         */
        delete: operations["api_v1_documents_share_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/access-requests/incoming/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Pending access requests across every active document the caller is an
         *     Owner of - an inbox, so an Owner needn't open each document to find
         *     them. Approve/deny still go through the per-document endpoints.
         */
        get: operations["api_v1_documents_access_requests_incoming_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/access-requests/mine/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The caller's own access requests in every status, newest first, so a
         *     requester can see whether theirs was approved or denied (``?document=``
         *     narrows to one document). Requests on documents since soft-deleted, or
         *     hidden in a trashed project, are left out.
         */
        get: operations["api_v1_documents_access_requests_mine_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/trash/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Soft-deleted documents the caller owns, most recently deleted first -
         *     exactly the ones ``DocumentRestoreAPIView`` would let them restore.
         */
        get: operations["api_v1_documents_trash_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Retrieve or update the requesting admin's own organization profile.
         *     Reachable without an active subscription, since fixing ``billing_email``
         *     is the prerequisite for checkout succeeding at all.
         */
        get: operations["api_v1_organizations_profile_retrieve"];
        /**
         * @description Retrieve or update the requesting admin's own organization profile.
         *     Reachable without an active subscription, since fixing ``billing_email``
         *     is the prerequisite for checkout succeeding at all.
         */
        put: operations["api_v1_organizations_profile_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Retrieve or update the requesting admin's own organization profile.
         *     Reachable without an active subscription, since fixing ``billing_email``
         *     is the prerequisite for checkout succeeding at all.
         */
        patch: operations["api_v1_organizations_profile_partial_update"];
        trace?: never;
    };
    "/api/v1/organizations/signup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Creates an Organization together with its first admin User, atomically,
         *     and logs the admin in immediately with a JWT pair.
         */
        post: operations["api_v1_organizations_signup_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Lists the org's projects (``?search=`` matches name); creates one -
         *     admin-only - granting the creator Owner access.
         */
        get: operations["api_v1_projects_list"];
        put?: never;
        /**
         * @description Lists the org's projects (``?search=`` matches name); creates one -
         *     admin-only - granting the creator Owner access.
         */
        post: operations["api_v1_projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Retrieve/update/soft-delete a project. A project outside the
         *     requester's organization, or a private one they have no resolvable
         *     access to, is a 404 either way; one they can see but can't act on at the
         *     requested level (read needs Viewer, write Editor, delete Owner) is a
         *     403.
         */
        get: operations["api_v1_projects_retrieve"];
        /**
         * @description Retrieve/update/soft-delete a project. A project outside the
         *     requester's organization, or a private one they have no resolvable
         *     access to, is a 404 either way; one they can see but can't act on at the
         *     requested level (read needs Viewer, write Editor, delete Owner) is a
         *     403.
         */
        put: operations["api_v1_projects_update"];
        post?: never;
        /**
         * @description Retrieve/update/soft-delete a project. A project outside the
         *     requester's organization, or a private one they have no resolvable
         *     access to, is a 404 either way; one they can see but can't act on at the
         *     requested level (read needs Viewer, write Editor, delete Owner) is a
         *     403.
         */
        delete: operations["api_v1_projects_destroy"];
        options?: never;
        head?: never;
        /**
         * @description Retrieve/update/soft-delete a project. A project outside the
         *     requester's organization, or a private one they have no resolvable
         *     access to, is a 404 either way; one they can see but can't act on at the
         *     requested level (read needs Viewer, write Editor, delete Owner) is a
         *     403.
         */
        patch: operations["api_v1_projects_partial_update"];
        trace?: never;
    };
    "/api/v1/projects/{id}/restore/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Reverses a soft-delete. Admin-only, like project creation - not gated
         *     on the project's own ProjectPermission rows. Cross-organization and
         *     already-active projects are both a 404.
         */
        post: operations["api_v1_projects_restore_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/share/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Lists a project's ``ProjectPermission`` grants, or grants/updates one
         *     for a target user - Owner-level access required. Granting an already-
         *     permitted user updates their level in place (never lowering the last
         *     Owner); each grant emails the target user.
         */
        get: operations["api_v1_projects_share_list"];
        put?: never;
        /**
         * @description Lists a project's ``ProjectPermission`` grants, or grants/updates one
         *     for a target user - Owner-level access required. Granting an already-
         *     permitted user updates their level in place (never lowering the last
         *     Owner); each grant emails the target user.
         */
        post: operations["api_v1_projects_share_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{id}/share/{user_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Revokes a ``ProjectPermission`` outright (row deletion, not a
         *     soft-delete). Owner-level access required; refuses to remove the
         *     project's last remaining Owner.
         */
        delete: operations["api_v1_projects_share_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/trash/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Soft-deleted projects in the admin's organization, most recently
         *     deleted first - the list ``ProjectRestoreAPIView`` restores from, and
         *     admin-only for the same reason.
         */
        get: operations["api_v1_projects_trash_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/checkout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Creates a Stripe Checkout Session for the requesting admin's
         *     organization and returns its URL for the frontend to redirect to.
         *
         *     Deliberately excludes ``HasActiveSubscription`` — an organization
         *     starting checkout has no subscription yet, that's the point.
         */
        post: operations["api_v1_subscriptions_checkout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/portal/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Creates a Stripe Customer Portal session for the requesting admin's
         *     organization - where they update payment details or cancel - and returns
         *     its URL for the frontend to redirect to. Reachable without an active
         *     subscription, so a lapsed organization can fix its payment method.
         */
        post: operations["api_v1_subscriptions_portal_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subscriptions/prices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Lists the plans an admin can pick from before starting checkout,
         *     cheapest first. Like checkout itself, reachable without an active
         *     subscription.
         */
        get: operations["api_v1_subscriptions_prices_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Lists the active members of the requesting user's own organization -
         *     e.g. to look up a teammate's id when sharing a project or document. Any
         *     authenticated org member may list, not just admins, but only an admin's
         *     response includes ``org_role``/``created`` - a regular member only needs
         *     an id and email to pick a share target.
         */
        get: operations["api_v1_users_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/deactivate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Admin-initiated soft-removal of a user within the requesting admin's own
         *     organization: sets ``is_active=False``, never a hard delete.
         *     Cross-organization targets are indistinguishable from missing ones.
         */
        delete: operations["api_v1_users_deactivate_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/reactivate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Reverses a deactivation within the requesting admin's organization.
         *     An already-active or cross-organization user is a 404.
         */
        post: operations["api_v1_users_reactivate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/role/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Promotes a member to admin or demotes an admin to member, within the
         *     requesting admin's own organization. An admin may not change their own
         *     role, which also guarantees the organization always keeps an admin.
         */
        patch: operations["api_v1_users_role_partial_update"];
        trace?: never;
    };
    "/api/v1/users/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Email/password → JWT pair, with a tight per-IP rate limit on top of the
         *     global anon throttle to blunt credential stuffing. Also sets the refresh
         *     token as an HttpOnly cookie.
         */
        post: operations["api_v1_users_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Blacklists the refresh token - from the body, else the cookie - so it
         *     can no longer be used, and clears the cookie.
         */
        post: operations["api_v1_users_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/auth/password-reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Sends a password-reset email if the address matches an existing user.
         *
         *     Always returns 200 regardless of whether the email matched, so the
         *     endpoint can't be used to enumerate registered accounts.
         */
        post: operations["api_v1_users_auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/auth/password-reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Validates the reset token and sets the user's new password. */
        post: operations["api_v1_users_auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Rotates a refresh token taken from the body or, when the body has
         *     none, from the HttpOnly cookie - and sets the rotated one back as the
         *     cookie.
         */
        post: operations["api_v1_users_auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/deactivated/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Deactivated users in the requesting admin's organization - the list
         *     ``ReactivateUserAPIView`` restores from.
         */
        get: operations["api_v1_users_deactivated_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/invitations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists and creates invitations, scoped to the requesting admin's organization. */
        get: operations["api_v1_users_invitations_list"];
        put?: never;
        /** @description Lists and creates invitations, scoped to the requesting admin's organization. */
        post: operations["api_v1_users_invitations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/invitations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * @description Revokes a pending invitation so its link stops working. The record is
         *     kept (status ``REVOKED``) rather than deleted.
         */
        delete: operations["api_v1_users_invitations_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/invitations/{id}/resend/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Re-sends a pending invitation with a new token and a fresh expiry
         *     window; the previously emailed link stops working.
         */
        post: operations["api_v1_users_invitations_resend_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/invitations/accept/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Creates the invitee's User account from a valid, pending invitation token
         *     and logs them in immediately with a JWT pair.
         */
        post: operations["api_v1_users_invitations_accept_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/invitations/bulk/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Creates invitations in bulk from an uploaded .xlsx file of email
         *     addresses, scoped to the requesting admin's organization.
         */
        post: operations["api_v1_users_invitations_bulk_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The requesting user's own profile. Deliberately reachable without an
         *     active subscription, so a client can tell an admin (send to billing) from
         *     a member (ask your admin) before any gated call returns 402.
         */
        get: operations["api_v1_users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description A signed-in user changes their own password. Every refresh token they
         *     hold is revoked - other devices are signed out - and a fresh pair is
         *     returned so the current session carries on.
         */
        post: operations["api_v1_users_me_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Container liveness/readiness probe.
         *
         *     Confirms the process is up and the database answers a trivial query;
         *     returns 200 ``{"status": "ok"}`` or 503 ``{"status": "unhealthy"}``.
         *     Deliberately hand-rolled — a full health-check framework is more than a
         *     single Postgres round-trip warrants here.
         */
        get: operations["healthz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `VIEWER` - Viewer
         *     * `EDITOR` - Editor
         *     * `OWNER` - Owner
         * @enum {string}
         */
        AccessLevelEnum: "VIEWER" | "EDITOR" | "OWNER";
        /** @description Read-only summary of a dj-stripe Subscription. */
        ActiveSubscription: {
            id: string;
            status: string;
            readonly interval: string | null;
            /** Format: date-time */
            readonly current_period_end: string | null;
            readonly cancel_at_period_end: boolean;
        };
        BillingPortalSessionResponse: {
            /** Format: uri */
            portal_url: string;
        };
        CheckoutSession: {
            price_id: string;
        };
        CheckoutSessionResponse: {
            /** Format: uri */
            checkout_url: string;
        };
        /**
         * @description The requesting user's own identity, role and organization - what a
         *     client needs after login to decide which screens to offer.
         */
        CurrentUser: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly org_role: components["schemas"]["OrgRoleEnum"];
            readonly organization: components["schemas"]["OrganizationSummary"] | null;
        };
        /**
         * @description ``created_by``, ``organization`` and ``project`` are always set server-side
         *     in the view (the latter after explicit org-scoped validation, and may be left
         *     unset entirely for a personal document) and never accepted from the client
         *     through this serializer. ``visibility`` is writable, but changing it on an
         *     existing document is Owner-only (enforced in the view).
         */
        Document: {
            readonly id: number;
            title: string;
            content?: string | null;
            visibility?: components["schemas"]["VisibilityEnum"];
            readonly access_level: (components["schemas"]["AccessLevelEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly created_by: number;
            /** Format: email */
            readonly created_by_email: string;
            readonly organization: number;
            readonly project: number | null;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
        };
        /**
         * @description Read-only - the view supplies ``document`` and ``requested_by`` from the
         *     URL and the requester, never from client-submitted data.
         */
        DocumentAccessRequest: {
            readonly id: number;
            readonly document: number;
            readonly document_title: string;
            readonly requested_by: number;
            /** Format: email */
            readonly requested_by_email: string;
            readonly reviewed_by: number | null;
            /** Format: email */
            readonly reviewed_by_email: string | null;
            /** @default PENDING */
            readonly status: components["schemas"]["DocumentAccessRequestStatusEnum"];
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
        };
        /**
         * @description * `PENDING` - Pending
         *     * `APPROVED` - Approved
         *     * `DENIED` - Denied
         * @enum {string}
         */
        DocumentAccessRequestStatusEnum: "PENDING" | "APPROVED" | "DENIED";
        /**
         * @description The create request: ``DocumentSerializer`` plus the optional ``project``
         *     to file the new document under (omitted or null for a personal document).
         *     The view resolves and checks that project itself - one the caller can't
         *     see is a 404, one they can't edit a 403 - so this field only documents
         *     the input; responses keep using ``DocumentSerializer``.
         */
        DocumentCreate: {
            readonly id: number;
            title: string;
            content?: string | null;
            visibility?: components["schemas"]["VisibilityEnum"];
            readonly access_level: (components["schemas"]["AccessLevelEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly created_by: number;
            /** Format: email */
            readonly created_by_email: string;
            readonly organization: number;
            project?: number | null;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
        };
        DocumentPermission: {
            readonly id: number;
            readonly document: number;
            readonly user: number;
            /** Format: email */
            readonly user_email: string;
            readonly access_level: components["schemas"]["AccessLevelEnum"];
        };
        InvitationAccept: {
            token: string;
            password: string;
        };
        /**
         * @description Creates a pending Invitation. `organization`, `invited_by`, `token`, and
         *     `status` are all set server-side — never accepted from the client.
         */
        InvitationCreate: {
            readonly id: number;
            /** Format: email */
            email: string;
            readonly organization: number;
            readonly invited_by: number | null;
            readonly token: string;
            readonly status: components["schemas"]["InvitationCreateStatusEnum"];
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly sent_at: string;
            /** Format: date-time */
            readonly accepted_at: string | null;
        };
        /**
         * @description * `PENDING` - Pending
         *     * `ACCEPTED` - Accepted
         *     * `EXPIRED` - Expired
         *     * `REVOKED` - Revoked
         * @enum {string}
         */
        InvitationCreateStatusEnum: "PENDING" | "ACCEPTED" | "EXPIRED" | "REVOKED";
        /**
         * @description Adds a password-length ceiling before the (unvalidated) auth check, so an
         *     oversized string can't reach the password hasher.
         */
        Login: {
            email: string;
            password: string;
        };
        /** @description ``refresh`` may be omitted when the refresh-token cookie carries it. */
        Logout: {
            refresh?: string;
        };
        /** @enum {unknown} */
        NullEnum: null;
        /**
         * @description * `ADMIN` - Admin
         *     * `MEMBER` - Member
         * @enum {string}
         */
        OrgRoleEnum: "ADMIN" | "MEMBER";
        /**
         * @description ``billing_email`` uniqueness is checked here so a collision returns 400
         *     rather than surfacing as an IntegrityError.
         */
        Organization: {
            readonly id: number;
            name: string;
            billing_email?: (string) | null;
            readonly active_subscription: components["schemas"]["ActiveSubscription"] | null;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
        };
        /** @description Input for creating an Organization together with its first admin User. */
        OrganizationSignup: {
            name: string;
            /** Format: email */
            billing_email?: string | null;
            /** Format: email */
            admin_email: string;
            admin_password: string;
        };
        /**
         * @description The slice of an organization any member may see about their own org:
         *     enough for a client to label it and to route an unpaid org to billing
         *     before hitting a 402.
         */
        OrganizationSummary: {
            readonly id: number;
            readonly name: string;
            readonly has_active_subscription: boolean;
        };
        PaginatedDocumentAccessRequestList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DocumentAccessRequest"][];
        };
        PaginatedDocumentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Document"][];
        };
        PaginatedDocumentPermissionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["DocumentPermission"][];
        };
        PaginatedInvitationCreateList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["InvitationCreate"][];
        };
        PaginatedPriceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Price"][];
        };
        PaginatedProjectList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Project"][];
        };
        PaginatedProjectPermissionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ProjectPermission"][];
        };
        PaginatedRosterUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["RosterUser"][];
        };
        PaginatedUserDetailList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["UserDetail"][];
        };
        /**
         * @description A signed-in user's own password change: the current password proves
         *     it's really them, the new one must pass the full password policy.
         */
        PasswordChange: {
            current_password: string;
            new_password: string;
        };
        PasswordResetConfirm: {
            uid: string;
            token: string;
            new_password: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        /**
         * @description ``created_by``, ``organization`` and ``project`` are always set server-side
         *     in the view (the latter after explicit org-scoped validation, and may be left
         *     unset entirely for a personal document) and never accepted from the client
         *     through this serializer. ``visibility`` is writable, but changing it on an
         *     existing document is Owner-only (enforced in the view).
         */
        PatchedDocument: {
            readonly id?: number;
            title?: string;
            content?: string | null;
            visibility?: components["schemas"]["VisibilityEnum"];
            readonly access_level?: (components["schemas"]["AccessLevelEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly created_by?: number;
            /** Format: email */
            readonly created_by_email?: string;
            readonly organization?: number;
            readonly project?: number | null;
            /** Format: date-time */
            readonly created?: string;
            /** Format: date-time */
            readonly modified?: string;
        };
        /**
         * @description ``billing_email`` uniqueness is checked here so a collision returns 400
         *     rather than surfacing as an IntegrityError.
         */
        PatchedOrganization: {
            readonly id?: number;
            name?: string;
            billing_email?: (string) | null;
            readonly active_subscription?: components["schemas"]["ActiveSubscription"] | null;
            /** Format: date-time */
            readonly created?: string;
            /** Format: date-time */
            readonly modified?: string;
        };
        /** @description Changes a member's organization role - the only writable field. */
        PatchedOrganizationRole: {
            org_role?: components["schemas"]["OrgRoleEnum"];
        };
        /**
         * @description ``created_by`` and ``organization`` are always set server-side from the
         *     request and never accepted from the client. ``visibility`` is writable, but
         *     changing it on an existing project is Owner-only (enforced in the view).
         */
        PatchedProject: {
            readonly id?: number;
            name?: string;
            description?: string | null;
            visibility?: components["schemas"]["VisibilityEnum"];
            readonly access_level?: (components["schemas"]["AccessLevelEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly created_by?: number;
            /** Format: email */
            readonly created_by_email?: string;
            readonly organization?: number;
            /** Format: date-time */
            readonly created?: string;
            /** Format: date-time */
            readonly modified?: string;
        };
        /**
         * @description A subscribable plan, as a client needs it to render a plan picker and
         *     pass ``id`` on to checkout. ``unit_amount`` is in the currency's smallest
         *     unit (e.g. cents).
         */
        Price: {
            readonly id: string;
            /** @description A brief description of the plan, hidden from customers. */
            readonly nickname: string;
            readonly product_name: string;
            readonly unit_amount: number | null;
            /** @description Three-letter ISO currency code */
            readonly currency: string;
            readonly interval: string | null;
        };
        /**
         * @description ``created_by`` and ``organization`` are always set server-side from the
         *     request and never accepted from the client. ``visibility`` is writable, but
         *     changing it on an existing project is Owner-only (enforced in the view).
         */
        Project: {
            readonly id: number;
            name: string;
            description?: string | null;
            visibility?: components["schemas"]["VisibilityEnum"];
            readonly access_level: (components["schemas"]["AccessLevelEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly created_by: number;
            /** Format: email */
            readonly created_by_email: string;
            readonly organization: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
        };
        ProjectPermission: {
            readonly id: number;
            readonly project: number;
            readonly user: number;
            /** Format: email */
            readonly user_email: string;
            readonly access_level: components["schemas"]["AccessLevelEnum"];
        };
        RosterUser: components["schemas"]["UserDetail"] | components["schemas"]["User"];
        /**
         * @description Validates a grant/re-share request: a target user (by id) and the
         *     ``AccessLevel`` to give them. The target user must belong to the same
         *     organization as the resource being shared - checked against
         *     ``context["organization"]``, which the view supplies from the resource
         *     it already resolved (and therefore already org-scoped).
         */
        Share: {
            user: number;
            access_level: components["schemas"]["AccessLevelEnum"];
        };
        /** @description Response shape for endpoints that log a user straight in. */
        TokenPair: {
            access: string;
            refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        /**
         * @description Minimal roster entry visible to every org member - just enough to pick
         *     a share target. Never accepts writes through this serializer.
         */
        User: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
        };
        /**
         * @description Adds role and join-date - admin-only, for actual user management
         *     rather than picking a share target.
         */
        UserDetail: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly org_role: components["schemas"]["OrgRoleEnum"];
            /** Format: date-time */
            readonly created: string;
        };
        /**
         * @description * `PRIVATE` - Private
         *     * `PUBLIC` - Public
         * @enum {string}
         */
        VisibilityEnum: "PRIVATE" | "PUBLIC";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_v1_documents_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Only documents filed under this project. */
                project?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumentList"];
                };
            };
        };
    };
    api_v1_documents_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["DocumentCreate"];
                "multipart/form-data": components["schemas"]["DocumentCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    api_v1_documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    api_v1_documents_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Document"];
                "application/x-www-form-urlencoded": components["schemas"]["Document"];
                "multipart/form-data": components["schemas"]["Document"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    api_v1_documents_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_documents_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedDocument"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedDocument"];
                "multipart/form-data": components["schemas"]["PatchedDocument"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    api_v1_documents_access_requests_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumentAccessRequestList"];
                };
            };
        };
    };
    api_v1_documents_access_requests_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DocumentAccessRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DocumentAccessRequest"];
                "multipart/form-data": components["schemas"]["DocumentAccessRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentAccessRequest"];
                };
            };
        };
    };
    api_v1_documents_access_requests_approve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentAccessRequest"];
                };
            };
        };
    };
    api_v1_documents_access_requests_deny_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentAccessRequest"];
                };
            };
        };
    };
    api_v1_documents_restore_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description The document's project is in the trash. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_documents_share_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumentPermissionList"];
                };
            };
        };
    };
    api_v1_documents_share_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Share"];
                "application/x-www-form-urlencoded": components["schemas"]["Share"];
                "multipart/form-data": components["schemas"]["Share"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPermission"];
                };
            };
        };
    };
    api_v1_documents_share_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_documents_access_requests_incoming_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumentAccessRequestList"];
                };
            };
        };
    };
    api_v1_documents_access_requests_mine_list: {
        parameters: {
            query?: {
                /** @description Only requests for this document. */
                document?: number;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumentAccessRequestList"];
                };
            };
        };
    };
    api_v1_documents_trash_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumentList"];
                };
            };
        };
    };
    api_v1_organizations_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    api_v1_organizations_profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Organization"];
                "application/x-www-form-urlencoded": components["schemas"]["Organization"];
                "multipart/form-data": components["schemas"]["Organization"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    api_v1_organizations_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedOrganization"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedOrganization"];
                "multipart/form-data": components["schemas"]["PatchedOrganization"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
        };
    };
    api_v1_organizations_signup_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationSignup"];
                "application/x-www-form-urlencoded": components["schemas"]["OrganizationSignup"];
                "multipart/form-data": components["schemas"]["OrganizationSignup"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    api_v1_projects_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectList"];
                };
            };
        };
    };
    api_v1_projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_v1_projects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_v1_projects_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Project"];
                "application/x-www-form-urlencoded": components["schemas"]["Project"];
                "multipart/form-data": components["schemas"]["Project"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_v1_projects_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_projects_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProject"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProject"];
                "multipart/form-data": components["schemas"]["PatchedProject"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_v1_projects_restore_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    api_v1_projects_share_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectPermissionList"];
                };
            };
        };
    };
    api_v1_projects_share_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Share"];
                "application/x-www-form-urlencoded": components["schemas"]["Share"];
                "multipart/form-data": components["schemas"]["Share"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPermission"];
                };
            };
        };
    };
    api_v1_projects_share_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_projects_trash_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectList"];
                };
            };
        };
    };
    api_v1_subscriptions_checkout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSession"];
                "application/x-www-form-urlencoded": components["schemas"]["CheckoutSession"];
                "multipart/form-data": components["schemas"]["CheckoutSession"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSessionResponse"];
                };
            };
            /** @description Invalid price, or organization has no billing email set. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_subscriptions_portal_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingPortalSessionResponse"];
                };
            };
            /** @description Organization has never subscribed, so has no billing account. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_subscriptions_prices_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPriceList"];
                };
            };
        };
    };
    api_v1_users_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRosterUserList"];
                };
            };
        };
    };
    api_v1_users_deactivate_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deactivated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An admin cannot deactivate their own account. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such user in your organization. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_users_reactivate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetail"];
                };
            };
        };
    };
    api_v1_users_role_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedOrganizationRole"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedOrganizationRole"];
                "multipart/form-data": components["schemas"]["PatchedOrganizationRole"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDetail"];
                };
            };
            /** @description Invalid role, or your own account. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such active user in your organization. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_users_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Login"];
                };
            };
        };
    };
    api_v1_users_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Logout"];
                "application/x-www-form-urlencoded": components["schemas"]["Logout"];
                "multipart/form-data": components["schemas"]["Logout"];
            };
        };
        responses: {
            /** @description Refresh token blacklisted. */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid refresh token. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_users_auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Always returned, match or not. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_users_auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirm"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Password changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired reset link. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_users_auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    api_v1_users_deactivated_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserDetailList"];
                };
            };
        };
    };
    api_v1_users_invitations_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedInvitationCreateList"];
                };
            };
        };
    };
    api_v1_users_invitations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["InvitationCreate"];
                "multipart/form-data": components["schemas"]["InvitationCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationCreate"];
                };
            };
        };
    };
    api_v1_users_invitations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitation revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invitation is no longer pending. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_users_invitations_resend_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationCreate"];
                };
            };
        };
    };
    api_v1_users_invitations_accept_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationAccept"];
                "application/x-www-form-urlencoded": components["schemas"]["InvitationAccept"];
                "multipart/form-data": components["schemas"]["InvitationAccept"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    api_v1_users_invitations_bulk_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Summary of created/skipped rows. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing file, invalid .xlsx, or row-count cap exceeded. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_v1_users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    api_v1_users_me_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChange"];
                "multipart/form-data": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Wrong current password, or new password rejected. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description {"status": "ok"} */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description {"status": "unhealthy"} */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
