from django.urls import path

from users.api.v1.views import (
    AccountDeleteAPIView,
    CookieTokenRefreshView,
    CurrentUserAPIView,
    DeactivatedUserListAPIView,
    DeactivateUserAPIView,
    EmailChangeConfirmAPIView,
    EmailChangeRequestAPIView,
    EmailVerificationConfirmAPIView,
    EmailVerificationResendAPIView,
    InvitationAcceptAPIView,
    InvitationBulkCreateAPIView,
    InvitationListCreateAPIView,
    InvitationResendAPIView,
    InvitationRevokeAPIView,
    LoginView,
    LogoutAPIView,
    OrganizationRoleUpdateAPIView,
    PasswordChangeAPIView,
    PasswordResetConfirmAPIView,
    PasswordResetRequestAPIView,
    ReactivateUserAPIView,
    RecoveryCodesRegenerateAPIView,
    TwoFactorConfirmAPIView,
    TwoFactorDisableAPIView,
    TwoFactorLoginAPIView,
    TwoFactorResetAPIView,
    TwoFactorSetupAPIView,
    TwoFactorStatusAPIView,
    UserListAPIView,
)

urlpatterns = [
    path("", UserListAPIView.as_view(), name="user_list"),
    path("me/", CurrentUserAPIView.as_view(), name="user_me"),
    path("me/password/", PasswordChangeAPIView.as_view(), name="user_password_change"),
    path("me/email/", EmailChangeRequestAPIView.as_view(), name="user_email_change"),
    path("me/delete/", AccountDeleteAPIView.as_view(), name="user_account_delete"),
    path(
        "me/verification-email/",
        EmailVerificationResendAPIView.as_view(),
        name="user_verification_email_resend",
    ),
    path("me/two-factor/", TwoFactorStatusAPIView.as_view(), name="user_two_factor"),
    path(
        "me/two-factor/setup/",
        TwoFactorSetupAPIView.as_view(),
        name="user_two_factor_setup",
    ),
    path(
        "me/two-factor/confirm/",
        TwoFactorConfirmAPIView.as_view(),
        name="user_two_factor_confirm",
    ),
    path(
        "me/two-factor/disable/",
        TwoFactorDisableAPIView.as_view(),
        name="user_two_factor_disable",
    ),
    path(
        "me/two-factor/recovery-codes/",
        RecoveryCodesRegenerateAPIView.as_view(),
        name="user_two_factor_recovery_codes",
    ),
    path(
        "deactivated/",
        DeactivatedUserListAPIView.as_view(),
        name="user_deactivated_list",
    ),
    path("auth/login/", LoginView.as_view(), name="auth_login"),
    path(
        "auth/login/two-factor/",
        TwoFactorLoginAPIView.as_view(),
        name="auth_login_two_factor",
    ),
    path("auth/refresh/", CookieTokenRefreshView.as_view(), name="auth_refresh"),
    path("auth/logout/", LogoutAPIView.as_view(), name="auth_logout"),
    path(
        "auth/password-reset/",
        PasswordResetRequestAPIView.as_view(),
        name="auth_password_reset",
    ),
    path(
        "auth/password-reset/confirm/",
        PasswordResetConfirmAPIView.as_view(),
        name="auth_password_reset_confirm",
    ),
    path(
        "auth/verify-email/",
        EmailVerificationConfirmAPIView.as_view(),
        name="auth_verify_email",
    ),
    path(
        "auth/confirm-email/",
        EmailChangeConfirmAPIView.as_view(),
        name="auth_confirm_email",
    ),
    path(
        "invitations/",
        InvitationListCreateAPIView.as_view(),
        name="invitation_list_create",
    ),
    path(
        "invitations/bulk/",
        InvitationBulkCreateAPIView.as_view(),
        name="invitation_bulk_create",
    ),
    path(
        "invitations/accept/",
        InvitationAcceptAPIView.as_view(),
        name="invitation_accept",
    ),
    path(
        "invitations/<int:pk>/",
        InvitationRevokeAPIView.as_view(),
        name="invitation_revoke",
    ),
    path(
        "invitations/<int:pk>/resend/",
        InvitationResendAPIView.as_view(),
        name="invitation_resend",
    ),
    path(
        "<int:pk>/deactivate/",
        DeactivateUserAPIView.as_view(),
        name="user_deactivate",
    ),
    path(
        "<int:pk>/reactivate/",
        ReactivateUserAPIView.as_view(),
        name="user_reactivate",
    ),
    path(
        "<int:pk>/two-factor/reset/",
        TwoFactorResetAPIView.as_view(),
        name="user_two_factor_reset",
    ),
    path(
        "<int:pk>/role/",
        OrganizationRoleUpdateAPIView.as_view(),
        name="user_role_update",
    ),
]
