# Generated by Django 6.1.2 on 2026-10-09 06:03

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_organization_last_expiry_reminder_sent_at"),
        ("projects", "0005_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("ACCESS_GRANTED", "Access granted"),
                            ("ACCESS_CHANGED", "Access changed"),
                            ("ACCESS_REVOKED", "Access removed"),
                            ("VISIBILITY_CHANGED", "Visibility changed"),
                            ("ACCESS_REQUEST_APPROVED", "Access request approved"),
                            ("ACCESS_REQUEST_DENIED", "Access request denied"),
                            ("ROLE_CHANGED", "Role changed"),
                            ("MEMBER_DEACTIVATED", "Member deactivated"),
                            ("MEMBER_REACTIVATED", "Member reactivated"),
                            ("INVITATION_SENT", "Invitation sent"),
                            ("INVITATION_RESENT", "Invitation resent"),
                            ("INVITATION_REVOKED", "Invitation revoked"),
                            ("INVITATION_ACCEPTED", "Invitation accepted"),
                            ("DELETED", "Moved to the trash"),
                            ("RESTORED", "Restored"),
                            ("ATTACHMENT_ADDED", "File attached"),
                            ("ATTACHMENT_DELETED", "File deleted"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="projects.document",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="projects.project",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events_about",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "-created"],
                        name="audit_audit_organiz_3808ca_idx",
                    )
                ],
            },
        ),
    ]
