# Generated by Django 6.1.2 on 2026-10-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="verb",
            field=models.CharField(
                choices=[
                    ("ACCESS_GRANTED", "Access granted"),
                    ("ACCESS_CHANGED", "Access changed"),
                    ("ACCESS_REVOKED", "Access removed"),
                    ("VISIBILITY_CHANGED", "Visibility changed"),
                    ("ACCESS_REQUEST_APPROVED", "Access request approved"),
                    ("ACCESS_REQUEST_DENIED", "Access request denied"),
                    ("ROLE_CHANGED", "Role changed"),
                    ("MEMBER_DEACTIVATED", "Member deactivated"),
                    ("MEMBER_REACTIVATED", "Member reactivated"),
                    ("INVITATION_SENT", "Invitation sent"),
                    ("INVITATION_RESENT", "Invitation resent"),
                    ("INVITATION_REVOKED", "Invitation revoked"),
                    ("INVITATION_ACCEPTED", "Invitation accepted"),
                    ("ACCOUNT_DELETED", "Account deleted"),
                    ("DELETED", "Moved to the trash"),
                    ("RESTORED", "Restored"),
                    ("ATTACHMENT_ADDED", "File attached"),
                    ("ATTACHMENT_DELETED", "File deleted"),
                ],
                max_length=30,
            ),
        ),
    ]
